// Central Definition of All System Permissions
// Format: MODULE_ACTION

const PERMISSIONS = {
  // User Management
  USER_CREATE: "USER.CREATE",
  USER_READ: "USER.READ",
  USER_UPDATE: "USER.UPDATE",
  USER_DELETE: "USER.DELETE",

  // Role Management (RBAC)
  ROLE_CREATE: "ROLE.CREATE",
  ROLE_READ: "ROLE.READ",
  ROLE_UPDATE: "ROLE.UPDATE",
  ROLE_DELETE: "ROLE.DELETE",
  ROLE_ASSIGN: "ROLE.ASSIGN",

  // Restaurant/Tenant Management
  RESTAURANT_CREATE: "RESTAURANT.CREATE",
  RESTAURANT_UPDATE: "RESTAURANT.UPDATE",
  RESTAURANT_READ: "RESTAURANT.READ",

  // Menu Management
  MENU_CREATE: "MENU.CREATE",
  MENU_READ: "MENU.READ",
  MENU_UPDATE: "MENU.UPDATE",
  MENU_DELETE: "MENU.DELETE",

  // Order Management
  ORDER_CREATE: "ORDER.CREATE",
  ORDER_READ: "ORDER.READ",
  ORDER_UPDATE: "ORDER.UPDATE",
  ORDER_DELETE: "ORDER.DELETE",

  // KDS
  KDS_VIEW: "KDS.VIEW",
  KDS_MANAGE: "KDS.MANAGE",

  // Reports
  REPORT_VIEW: "REPORT.VIEW",
  REPORT_EXPORT: "REPORT.EXPORT",

  //item
  ITEM_CREATE: "ITEM.CREATE",
  ITEM_READ: "ITEM.READ",
  ITEM_UPDATE: "ITEM.UPDATE",
  ITEM_DELETE: "ITEM.DELETE",

  //category
  CATEGORY_CREATE: "CATEGORY.CREATE",
  CATEGORY_READ: "CATEGORY.READ",
  CATEGORY_UPDATE: "CATEGORY.UPDATE",
  CATEGORY_DELETE: "CATEGORY.DELETE",

  //customization
  CUSTOMIZATION_CREATE: "CUSTOMIZATION.CREATE",
  CUSTOMIZATION_READ: "CUSTOMIZATION.READ",
  CUSTOMIZATION_UPDATE: "CUSTOMIZATION.UPDATE",
  CUSTOMIZATION_DELETE: "CUSTOMIZATION.DELETE",

  //discount
  DISCOUNT_CREATE: "DISCOUNT.CREATE",
  DISCOUNT_READ: "DISCOUNT.READ",
  DISCOUNT_UPDATE: "DISCOUNT.UPDATE",
  DISCOUNT_DELETE: "DISCOUNT.DELETE",

  //Tax
  TAX_CREATE: "TAX.CREATE",
  TAX_READ: "TAX.READ",
  TAX_UPDATE: "TAX.UPDATE",
  TAX_DELETE: "TAX.DELETE",
};

const MODULES = {
  USER: "USER",
  ROLE: "ROLE",
  RESTAURANT: "RESTAURANT",
  MENU: "MENU",
  ORDER: "ORDER",
  KDS: "KDS",
  REPORT: "REPORT",
};

module.exports = {
  PERMISSIONS,
  MODULES,
};
